In [2]:
import numpy as np  

In [4]:
%pip install -Uq pymcel

In [5]:
import pymcel as pc 

Bienvenido a PyMCel v0.9.10 ¡al infinito y más allá!


In [6]:
%pip install -Uq rebound

In [8]:
%pip install -Uq pandas

In [9]:
%pip install -Uq plotly

In [10]:
%pip install -Uq nbformat

In [18]:
tabla_sol, jd_sol, X_sol = pc.consulta_horizons(
    id='399',
    location ='@SSB',
    epochs = '2026-02-26 00:00:00',
)

X_sol

array([-1.36760992e+11,  5.69736004e+10,  1.54399974e+07, -1.20847455e+04,
       -2.75376663e+04,  1.83171431e+00])

In [15]:
tabla_jup, jd_jup, X_jup = pc.consulta_horizons(
    id='Jupiter Barycenter',
    location='@SSB',
    epochs='2026-02-26 00:00:00',
)

print("Jupiter position (X_jup):")
print(X_jup)

Jupiter position (X_jup):
[-3.13499559e+11  7.16531655e+11  4.04379637e+09 -1.21253772e+04
 -4.61863891e+03  2.90510926e+02]


In [21]:
r_sol_0 = X_sol[:3]  # Posición del Sol
r_jup_0 = X_jup[:3]  # Posición de Júpiter

v_sol_0 = X_sol[3:]  # Velocidad del Sol
v_jup_0 = X_jup[3:]  # Velocidad de Júpiter

In [23]:
deltat = 1*86400  # Un día en segundos

r_jup_dt = r_jup_0 + v_jup_0 * deltat
r_sol_dt = r_sol_0 + v_sol_0 * deltat

r_jup_0, r_jup_dt


(array([-3.13499559e+11,  7.16531655e+11,  4.04379637e+09]),
 array([-3.14547192e+11,  7.16132604e+11,  4.06889651e+09]))

In [25]:
import numpy as np 

In [27]:
mu_sol = pc.constantes.mu_sun
mu_jup = pc.constantes.mu_jupiter

rij_vec = r_jup_0 - r_sol_0
v_jup_dt = v_jup_0 - mu_sol * rij_vec / np.linalg.norm(rij_vec)**3 * deltat
v_jup_dt

array([-12119.01211262,  -4642.39214251,    290.36584886])

In [28]:
#Velocidad del Sol en t+deltat usando la misma aproximación

rij_vec_sol = r_sol_0 - r_jup_0
v_sol_dt = v_sol_0 - mu_jup * rij_vec_sol / np.linalg.norm(rij_vec_sol)**3 * deltat
v_sol_dt

array([-1.20847515e+04, -2.75376436e+04,  1.83185283e+00])